version: "3"

services:
  transp-postgres:
    image: "postgres:13.0-alpine"
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

volumes:
  postgres: